"""Initial schema

Revision ID: d8396f9e3c57
Revises:
Create Date: 2025-12-15 02:48:15.631256

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8396f9e3c57"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("real_name", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("metadata", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_author_id"), "authors", ["author_id"], unique=True)
    op.create_table(
        "jokes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("joke_uuid", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("structure", sa.String(length=50), nullable=True),
        sa.Column("maturity_rating", sa.String(length=10), nullable=False),
        sa.Column("cognitive_type", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.String(), nullable=False),
        sa.Column("flags", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("source_platform", sa.String(length=50), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("scraped_date", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("added_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("engagement", sa.String(), nullable=True),
        sa.Column("gtvh", sa.String(), nullable=True),
        sa.Column("metadata", sa.String(), nullable=True),
        sa.Column("weighted_avg_funniness", sa.Float(), nullable=True),
        sa.Column("weighted_avg_quality", sa.Float(), nullable=True),
        sa.Column("total_ratings_count", sa.Integer(), nullable=False),
        sa.Column("text_preview", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jokes_joke_uuid"), "jokes", ["joke_uuid"], unique=True)
    op.create_table(
        "joke_author_link",
        sa.Column("joke_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["joke_id"],
            ["jokes.id"],
        ),
        sa.PrimaryKeyConstraint("joke_id", "author_id"),
    )
    op.create_table(
        "joke_category_link",
        sa.Column("joke_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["joke_id"],
            ["jokes.id"],
        ),
        sa.PrimaryKeyConstraint("joke_id", "category"),
    )
    op.create_table(
        "joke_linguistic_mechanism_link",
        sa.Column("joke_id", sa.Integer(), nullable=False),
        sa.Column("mechanism", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["joke_id"],
            ["jokes.id"],
        ),
        sa.PrimaryKeyConstraint("joke_id", "mechanism"),
    )
    op.create_table(
        "rating_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("joke_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("min_rating", sa.Float(), nullable=False),
        sa.Column("max_rating", sa.Float(), nullable=False),
        sa.Column("total_ratings", sa.Integer(), nullable=False),
        sa.Column("avg_funniness", sa.Float(), nullable=False),
        sa.Column("avg_quality", sa.Float(), nullable=True),
        sa.Column("normalized_avg_funniness", sa.Float(), nullable=False),
        sa.Column("normalized_avg_quality", sa.Float(), nullable=True),
        sa.Column("metadata", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["joke_id"],
            ["jokes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rating_sources_joke_id"), "rating_sources", ["joke_id"], unique=False)
    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating_source_id", sa.Integer(), nullable=False),
        sa.Column("funniness", sa.Float(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rating_source_id"],
            ["rating_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_votes_rating_source_id"), "votes", ["rating_source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_rating_source_id"), table_name="votes")
    op.drop_table("votes")
    op.drop_index(op.f("ix_rating_sources_joke_id"), table_name="rating_sources")
    op.drop_table("rating_sources")
    op.drop_table("joke_linguistic_mechanism_link")
    op.drop_table("joke_category_link")
    op.drop_table("joke_author_link")
    op.drop_index(op.f("ix_jokes_joke_uuid"), table_name="jokes")
    op.drop_table("jokes")
    op.drop_index(op.f("ix_authors_author_id"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
